# -*- coding: utf-8 -*-
"""fashion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y584FbXQtN3rK8-0XlhjpPGEgVXhrqQy
"""

# Step 1: Import libraries
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

# Step 2: Load the Fashion MNIST dataset
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Step 3: Preprocess - Normalize pixel values
X_train = X_train / 255.0
X_test = X_test / 255.0

# Expand dimensions to add channel information (because CNN expects 3D input)
X_train = X_train[..., np.newaxis]
X_test = X_test[..., np.newaxis]

# Step 4: Define class names
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# Step 5: Build the CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D((2,2)),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2,2)),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')  # 10 output categories
])

# Step 6: Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Step 7: Train the model
history = model.fit(X_train, y_train, epochs=10, validation_split=0.2, batch_size=64, verbose=1)

# Step 8: Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Make predictions
y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)

# Plot some images with predictions
plt.figure(figsize=(15,10))
for i in range(20):
    plt.subplot(4,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(X_test[i].reshape(28,28), cmap=plt.cm.binary)
    color = 'green' if y_pred_classes[i] == y_test[i] else 'red'
    plt.xlabel(f"Pred: {class_names[y_pred_classes[i]]}\nTrue: {class_names[y_test[i]]}", color=color)

plt.tight_layout()
plt.show()